name: Support new device / incorect display of device
description: Support new device / incorect display of device.
body:
  - type: input
    id: product
    attributes:
      label: Product (manufacturer, model)
    validations:
      required: true
  - type: input
    id: display-as
    attributes:
      label: As what should be displayed? Switch? Dimmer? Blind with positioning? Blind without positioning? Etc.
    validations:
      required: true
  - type: textarea
    id: api-response
    attributes:
      label: API response for this device
      render: code
      description: |
        Past here response API response for this device. To get API response, open in browser: http://FIBARO-IP/api/devices/DEVICE-ID (replace FIBARO-IP with your Home Center IP and DEVICE-ID with device ID) and login. Device ID you can check in Fibaro panel or directly in HomeKit device information (serial number field).
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Any aditional info.
    validations:
      required: false
